---
title: "ST558 Project 1"
author: "M. Sweitzer, M. Beebe"
format: html
editor: visual
---

# Data processing first steps

## Data set EDU01a

### Import the Data

```{r, echo=FALSE}
suppressPackageStartupMessages(library(tidyverse))
```


```{r}
library(tidyverse)
library(readr)
census_1a_original <- read_csv("https://www4.stat.ncsu.edu/~online/datasets/EDU01a.csv")
head(census_1a_original)
#view(census_1a_original)
```

### Select and Pivot

```{r}
census_1a_condensed <- census_1a_original |>
  select(Area_name, STCOU, ends_with("D")) |>
  rename(area_name = Area_name) |>
  pivot_longer(cols = 3:12, 
               names_to = "education_id", 
               values_to = "measurement")
head(census_1a_condensed) 
#view(census_1a_condensed)
```

### Add year and survey code columns

```{r}
census_1a_add <- census_1a_condensed |>
  mutate(year = (as.numeric(substr(education_id, 8, 9)) + 1900),
         education_survey_code = substr(education_id, 1, 7))
census_1a_add
```

### Create two datasets with non-county and county level data



### Add new variable for county level tibble




### Add new variable for non-county level tibble




# Data processing function creation

```{r}
#need to make more generic (pivot column name) and add optional argument, maybe 
# need to have a named tibble that can be returned so it can be used later?
process_data1 <- function(tibble_df) {
  tibble_df |>
    select(Area_name, STCOU, ends_with("D")) |>
    rename(area_name = Area_name) |>
    pivot_longer(cols = 3:12, 
                 names_to = "education_id", 
                 values_to = "measurement")
}
process_data1(census_1a_original)
```



